-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR,
       MONTH(SALES_DATE) MONTH,
       COUNT(DISTINCT(S.USER_ID)) PURCHASED_USERS,
       ROUND(COUNT(DISTINCT(S.USER_ID))/TOTAL_USERS, 1) PUCHASED_RATIO
FROM USER_INFO I
JOIN ONLINE_SALE S ON I.USER_ID=S.USER_ID
JOIN (
    SELECT COUNT(USER_ID) TOTAL_USERS
    FROM USER_INFO
    WHERE YEAR(JOINED)=2021
) AS TMP
WHERE YEAR(JOINED)=2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH