-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, T.MAX-D.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA D
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS T
ON YEAR(D.DIFFERENTIATION_DATE)=T.YEAR
ORDER BY YEAR, YEAR_DEV;