-- 코드를 입력하세요

SELECT CAR_ID, C.CAR_TYPE, DAILY_FEE*(1-(0.01*DISCOUNT_RATE))*30 FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE='30일 이상' AND (CAR_TYPE='세단' OR CAR_TYPE='SUV')
) AS RATE ON C.CAR_TYPE=RATE.CAR_TYPE
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    GROUP BY CAR_ID
) AND (DAILY_FEE*(1-(0.01*DISCOUNT_RATE))*30 BETWEEN 500000 AND 1999999)
ORDER BY FEE DESC, C.CAR_TYPE, CAR_ID DESC;