-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M ON R.MEMBER_ID=M.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*)=(
        SELECT COUNT(*) C
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY C DESC
        LIMIT 1
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;