-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS TMP ON F.FLAVOR=TMP.FLAVOR
ORDER BY (F.TOTAL_ORDER+TMP.TOTAL_ORDER) DESC
LIMIT 3;