-- 코드를 입력하세요
WITH RECURSIVE H AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM H
    WHERE HOUR<23
)

SELECT H.HOUR, IFNULL(T.COUNT, 0) AS COUNT
FROM H
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) AS T ON H.HOUR=T.HOUR