-- 코드를 작성해주세요
CREATE TABLE BONUS_POLICY (MIN_SCORE INT, GRADE VARCHAR(2), BONUS_PCT DOUBLE);
INSERT INTO BONUS_POLICY VALUES (96, 'S', 0.20);
INSERT INTO BONUS_POLICY VALUES (90, 'A', 0.15);
INSERT INTO BONUS_POLICY VALUES (80, 'B', 0.10);
INSERT INTO BONUS_POLICY VALUES (0, 'C', 0.0);

SELECT E.EMP_NO, EMP_NAME, G.GRADE, (BONUS_PCT*SAL) AS BONUS
FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO,
        CASE 
            WHEN AVG(SCORE) >= 96 THEN 'S'
            WHEN AVG(SCORE) >= 90 THEN 'A'
            WHEN AVG(SCORE) >= 80 THEN 'B'
            ELSE 'C'
        END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS G ON E.EMP_NO=G.EMP_NO
JOIN BONUS_POLICY P ON P.GRADE=G.GRADE
ORDER BY E.EMP_NO;

