-- 코드를 입력하세요
SELECT HISTORY_ID, 
       DAILY_FEE*(DATEDIFF(END_DATE, START_DATE)+1)*
       (CASE
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN 1-0.01*(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='90일 이상')
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN 1-0.01*(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='30일 이상')
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN 1-0.01*(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='7일 이상')
        ELSE 1
       END) FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID=C.CAR_ID
WHERE CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;