-- 코드를 작성해주세요
SELECT TMP.ID, NAME.FISH_NAME, TMP.LENGTH
FROM (
    SELECT 
        *,
        RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS R
    FROM FISH_INFO
) AS TMP
JOIN FISH_NAME_INFO NAME ON TMP.FISH_TYPE=NAME.FISH_TYPE
WHERE R=1
ORDER BY TMP.ID;