-- 코드를 입력하세요

SELECT I.FOOD_TYPE, REST_ID, REST_NAME, I.FAVORITES
FROM REST_INFO I
JOIN (
    SELECT MAX(FAVORITES) AS FAVORITES, FOOD_TYPE
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS T ON I.FOOD_TYPE=T.FOOD_TYPE
WHERE I.FAVORITES=T.FAVORITES
ORDER BY FOOD_TYPE DESC;