-- 코드를 입력하세요
# SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY CATEGORY
# ORDER BY MAX_PRICE DESC


SELECT F.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT MAX(PRICE) AS MAX_PRICE, CATEGORY
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    ) AS T ON F.CATEGORY=T.CATEGORY
WHERE PRICE=MAX_PRICE AND F.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC